steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcs-to-bigquery', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'gcs-to-bigquery',
         '--image', 'gcr.io/$PROJECT_ID/gcs-to-bigquery',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--no-allow-unauthenticated',
         '--trigger-topic=firemai-gcs-bq-trigger']