steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/load-api-to-gcs', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'load-api-to-gcs',
         '--image', 'gcr.io/$PROJECT_ID/load-api-to-gcs',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--no-allow-unauthenticated']